/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 The sidebars can be generated from the filesystem, or explicitly defined here.
 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebar = {
    snapSidebar: [
      "index",
      {
        type: "category",
        label: "Get started",
        link: { type: "generated-index" },
        collapsed: false,
        items: [{ type: "autogenerated", dirName: "get-started" }],
      },
      {
        type: "category",
        label: "How to",
        link: { type: "generated-index" },
        items: [{ type: "autogenerated", dirName: "how-to" }],
      },
      {
        type: "category",
        label: "Concepts",
        link: { type: "generated-index" },
        items: [{ type: "autogenerated", dirName: "concepts" }],
      },
    ],
  };
    
  module.exports = sidebar;